
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public
    username: postgres
    password: postgress
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: vetenhuseynov2000@gmail.com
    password:  zmzduenzoeybufkc
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8080

logging:
  level:
    org.springframework: info
    org.hibernate: info

